name: FTP Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Installation des dépendances
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Installation des dépendances FTP
      run: sudo apt-get install -y lftp

    - name: Déploiement FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        SOURCE_DIR="build/"
        DEST_DIR="www/"
        
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; set ftp:ssl-force true; set ftp:ssl-protect-data true; mirror -e -R $SOURCE_DIR $DEST_DIR --verbose"